### PR TITLE
Strict Cast, castings tests, and bug fixes

### LINKED ISSUE #174: Fix strict cast
A strict cast should throw an error if it is of the wrong type.

See: https://cql.hl7.org/09-b-cqlreference.html#as

### PR DESCRIPTION
**Pull request by cmoesel**
This implements strict cast (throw an error instead of return null), aiming to have helpful errors.

In addition, it turns out we had no tests for casting, so I added them.

And adding tests uncovered a few bugs which are now fixed.

Fixes #174 

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository.
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [x] Code passes lint and prettier (hint: use `yarn run test:plus` to run tests, lint, and prettier)
- [x] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [x] `cql4browsers.js` built with `yarn run build:browserify` if source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

File: examples/browser/cql4browsers.js [hunk 1]
```diff
@@ -11766,15 +11766,13 @@ var As = /*#__PURE__*/function (_Expression) {
         return null;
       }
 
-      if (typeof arg._is !== 'function' && !isSystemType(this.asTypeSpecifier)) {
-        // We need an _is implementation in order to check non System types
-        // If this is not found then we should just return the arg to match old functionality.
-        return arg;
-      }
-
```
Comment (cmoesel) [inline examples/browser/cql4browsers.js:11774]: Turns out we did not need this because it more or less shakes out in the implementation of `ctx.matchesTypeSpecifier`.

File: examples/browser/cql4browsers.js [hunk 2]
```diff
@@ -12659,6 +12657,133 @@ function isSystemType(spec) {
...
+          name: k,
+          elementType: guessSpecifierType(val[k])
+        };
+      })
+    };
+  }
+
+  return 'Unknown';
+}
+
```
Comment (cmoesel) [inline examples/browser/cql4browsers.js:12786]: All this code just to get nice error messages.  _(sigh)_.

File: src/elm/type.js [hunk 3]
```diff
@@ -29,14 +29,13 @@ class As extends Expression {
     if (arg == null) {
       return null;
     }
-    if (typeof arg._is !== 'function' && !isSystemType(this.asTypeSpecifier)) {
-      // We need an _is implementation in order to check non System types
-      // If this is not found then we should just return the arg to match old functionality.
-      return arg;
-    }
```
Comment (cmoesel) [inline src/elm/type.js:36]: Turns out we did not need this because it more or less shakes out in the implementation of `ctx.matchesTypeSpecifier`.

File: src/elm/type.js [hunk 4]
```diff
@@ -536,6 +535,80 @@ function isSystemType(spec) {
...
+    };
+  } else if (typeof val === 'object' && Object.keys(val).length > 0) {
+    return {
+      type: 'TupleTypeSpecifier',
+      element: Object.keys(val).map(k => ({ name: k, elementType: guessSpecifierType(val[k]) }))
+    };
+  }
+  return 'Unknown';
+}
+
```
Comment (cmoesel) [inline src/elm/type.js:611]: All this code just to get nice error messages. _(sigh)._

File: src/runtime/context.js [hunk 5]
```diff
@@ -295,7 +303,21 @@ class Context {
...
+        if (Array.isArray(val) || val.isInterval) {
+          return false;
+        }
+        // Otherwise just default to true to match legacy behavior.
+        //
+        // NOTE: This is also where arbitrary tuples land because they will not have
+        // an "is" function and we don't encode the type information into the runtime
+        // objects so we can't easily determine their type. We can't reject them,
+        // else things like `Encounter{ id: "1" } is Encounter` would return false.
+        // So for now we allow false positives in order to avoid false negatives.
```
Comment (cmoesel) [inline src/runtime/context.js:320]: I think if/when we want to fix this for named tuples, we need to introduce a new API function in PatientSource that allows cql-execution to pass it a Tuple and have it return back a wrapped version of the Tuple signifying the appropriate type.  That's kind of a big deal, so punting for now.

**Review by kjmahalingam — APPROVED** [review]
Awesome! This looks comprehensive, and your explanations in code comments and PR comments are thorough and helped me understand some complexities. Good work!
