### PR TITLE
Arithmetic fixes

### LINKED ISSUE #49: Test cases for variance and population variance are reversed
_From @brynrhodes on August 30, 2016 16:35_

[CQLIT-18](https://oncprojectracking.healthit.gov/support/browse/CQLIT-18)

CQL > variance and pop variance

Erich Schulz: i think the 2 test case values are reversed...

Erich Schulz:
// PopulationVariance
// should be able to find PopulationVariance of a list
PopulationVariance_v: 2.5,

// Variance
// should be able to find Variance of a list
Variance_v: 2,
Erich Schulz: i have a test spreadsheet here

Erich Schulz:
// @Test: Variance
define Variance_v: Variance(
{1,2,3,4,5}

)
// @Test: PopulationVariance
define PopulationVariance_v: PopulationVariance(
{1.0,2.0,3.0,4.0,5.0}

)

_Copied from original issue: cqframework/clinical_quality_language#64_

### LINKED ISSUE #182: StdDev and PopulationStdDev implementations are swapped
See: https://cql.hl7.org/STU4/09-b-cqlreference.html#population-stddev
See: https://cql.hl7.org/STU4/09-b-cqlreference.html#stddev

### LINKED ISSUE #183: Divide broken when numerator is Quantity and denominator is Decimal
See `CqlArithmeticFunctionsTest.Divide.Divide1Q1` test in `spec-tests`.

### LINKED ISSUE #184: Invalid math operations returning NaN instead of null
Applies to `log`, `ln`, and `modulo`.  See the following spec-tests:
* CqlArithmeticFunctionsTest.Log.Log1Base1
* CqlArithmeticFunctionsTest.Ln.LnNeg1
* CqlArithmeticFunctionsTest.Modulo.Modulo0By0

### LINKED ISSUE #188: Truncate gives wrong answer for negative Decimals
Negative decimals should be truncated toward zero, but they're getting floored instead.

E.g., `Truncate(-1.1)` should be `-1`, but currently returns `-2`.

See spec-tests:
* CqlArithmeticFunctionsTest.Truncate.TruncateNeg1D1
* CqlArithmeticFunctionsTest.Truncate.TruncateNeg1D9

### LINKED ISSUE #189: TruncatedDivide gives wrong answer for negative Decimals
Similar problem as #188.  See spec tests:
* CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivideNeg10By3
* CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivideNeg10d1By3D1
* CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivide10ByNeg3
* CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivide10d1ByNeg3D1

### PR DESCRIPTION
**Pull request by kjmahalingam**
Various fixes to tests and/or logic to address the following test failures:

| **Test** | **Error** |
|---|---|
| CqlAggregateFunctionsTest.PopulationStdDev.PopStdDevTest1 | Wrong answer (swapped w/ StdDev) |
| CqlAggregateFunctionsTest.PopulationVariance.PopVarianceTest1 | Wrong answer (swapped w/ Variance) |
| CqlAggregateFunctionsTest.StdDev.StdDevTest1 | Wrong answer (swapped w/ PopulationStdDev) |
| CqlAggregateFunctionsTest.Variance.VarianceTest1 | Wrong answer (swapped w/ PopulationVariance) |
| CqlArithmeticFunctionsTest.Divide.Divide1Q1 | Wrong answer (by a LOT) |
| CqlArithmeticFunctionsTest.Log.Log1Base1 | Wrong answer (NaN vs null) |
| CqlArithmeticFunctionsTest.Ln.LnNeg1 | Wrong answer (NaN vs null) |
| CqlArithmeticFunctionsTest.Modulo.Modulo0By0 | Wrong answer (NaN vs null) |
| CqlArithmeticFunctionsTest.Truncate.TruncateNeg1D1 | Wrong answer (-2 vs -1) |
| CqlArithmeticFunctionsTest.Truncate.TruncateNeg1D9 | Wrong answer (-2 vs -1) |
| "CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivideNeg10By3" | Wrong answer (-4 vs -3) |
| "CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivideNeg10d1By3D1" | Wrong answer (-4 vs -3) |
| "CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivide10ByNeg3" | Wrong answer (-4 vs -3) |
| "CqlArithmeticFunctionsTest.Truncated Divide.TruncatedDivide10d1ByNeg3D1" | Wrong answer (-4 vs -3) |

Fixes #184
Fixes #188
Fixes #189
Fixes #183
Fixes #182
Fixes #49

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository.
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [x] Code passes lint and prettier (hint: use `yarn run test:plus` to run tests, lint, and prettier)
- [x] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [x] `cql4browsers.js` built with `yarn run build:browserify` if source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

File: src/datatypes/quantity.js [hunk 1]
```diff
@@ -107,18 +107,30 @@ class Quantity {
...
+          return null;
+        }
+        try {
+          return new Quantity(decimalAdjust('round', value, -8), coalesceToOne(this.unit));
+        } catch (e) {
+          return null;
+        }
+      } else {
+        const a = this.unit != null ? this : new Quantity(this.value, '1');
+        const b = other.unit != null ? other : new Quantity(other.value, '1');
```
Comment (cmoesel) [inline src/datatypes/quantity.js:122]: I don't know if this can happen, but if `other.unit` is null, it will convert to `'1'`.  If that happens will we end up w/ a similar issue as before.

Or, in other words, should line 110 above also check for `other.unit == null`?

File: src/elm/arithmetic.js [hunk 2]
```diff
@@ -279,7 +302,12 @@ class Log extends Expression {
       return null;
     }
 
-    return args.reduce((x, y) => Math.log(x) / Math.log(y));
+    const log = args.reduce((x, y) => Math.log(x) / Math.log(y));
+
+    if (!MathUtil.isValidDecimal(log)) {
+      return null;
+    }
+    return log;
```
Comment (cmoesel) [inline src/elm/arithmetic.js:310]: This is the third time I've seen this pattern in this file.  I'd consider making a function to handle this pattern (`nanToNull` or `suppressNaN` or `decimalOrNull` or something like that).

**Review by cmoesel — COMMENTED** [review]
This is awesome.  Nice work!  I had a couple of comments to consider.  Let me know what you think...

File: src/datatypes/quantity.js (hunk 1 above)
Comment (kjmahalingam) [reply src/datatypes/quantity.js:122]: Done!

File: src/elm/arithmetic.js (hunk 2 above)
Comment (kjmahalingam) [reply src/elm/arithmetic.js]: I added `decimalOrNull` to the `MathUtil` file and used it to replace this repetitive pattern.

**Comment by kjmahalingam** [comment]
@cmoesel This should be ready for re-review.

**Comment by kjmahalingam** [comment]
I believe the codecov report indicates that there is slight change to the coverage in the quantity.js file. That being said, I don't think there's any other testing to add there. We re-added the test cases that are associated with the new code. If any concerns, let me know.

**Review by cmoesel — APPROVED** [review]
Awesome.  A pile of bugs obliterated by @kjmahalingam!
