### PR TITLE
More arithmetic fixes

### LINKED ISSUE #185: Check Decimal Min/Max Values for Correctness
The spec-tests are failing.  Check implementation for correctness (may be related to limitations of JavaScript number:
* CqlArithmeticFunctionsTest.MinValue.DecimalMinValue
* CqlArithmeticFunctionsTest.MaxValue.DecimalMaxValue

### LINKED ISSUE #187: Power(null, null) provides wrong answer
Should be null but 1 is returned.

See spec test: `CqlArithmeticFunctionsTest.Power.PowerNullToNull`

### PR DESCRIPTION
**Pull request by kjmahalingam**
Various fixes to tests and/or logic to address the following test failures:

| **Test** | **Error** |
| --- | --- |
| CqlArithmeticFunctionsTest.MinValue.DecimalMinValue | Wrong answer (-1e+29 vs -1e+28) |
| CqlArithmeticFunctionsTest.MaxValue.DecimalMaxValue |Wrong answer (1e+29 vs 1e+28) |
| CqlArithmeticFunctionsTest.Power.PowerNullToNull | Wrong answer (1 vs null) |

Fixes #187
Fixes #185

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository.
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [ ] Code coverage has not gone down and all code touched or added is covered.
- [x] Code passes lint and prettier (hint: use `yarn run test:plus` to run tests, lint, and prettier)
- [x] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [x] `cql4browsers.js` built with `yarn run build:browserify` if source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

File: src/util/math.js [hunk 1]
```diff
@@ -11,8 +11,8 @@ const { Uncertainty } = require('../datatypes/uncertainty');
 
 const MAX_INT_VALUE = Math.pow(2, 31) - 1;
 const MIN_INT_VALUE = Math.pow(-2, 31);
-const MAX_FLOAT_VALUE = 99999999999999999999999999999.99999999;
-const MIN_FLOAT_VALUE = -99999999999999999999999999999.99999999;
+const MAX_FLOAT_VALUE = 9999999999999999999999999999.99999999;
+const MIN_FLOAT_VALUE = -9999999999999999999999999999.99999999;
```
Comment (cmoesel) [inline src/util/math.js:15]: So, here's a plot twist.  In looking into this further for this PR, it seems that:
* Yes, the CQL execution values were _wrong_
* BUT, the spec test values are _also wrong_!

According to [CQL Spec](http://build.fhir.org/ig/HL7/cql/09-b-cqlreference.html#maximum):
* Max: `(10^28 – 1) / 10^8`  => `99999999999999999999.99999999`
* Min: `(-10^28 + 1) / 10^8` => `-99999999999999999999.99999999`

I've also confirmed that the decimal equivalents of the scientific notation in the spec are correct.  So... we need to fix the values here in the code as well as in the tests.

**Review by cmoesel — CHANGES_REQUESTED** [review]
Look in the individual comments for a surprising plot twist!

File: src/util/math.js (hunk 1 above)
Comment (kjmahalingam) [reply src/util/math.js:15]: I have to wonder how we got all of these different representations all over! I'll fix it now.
